### ISSUE TITLE
Transparency issues with Direct3D11 under Unity 2019.3.0f3

### ISSUE THREAD

**Issue by Armitage1982** [kirurobo/UniWinApiAsset#6]
Hi,

Screen background stay black and opaque when using **Direct3D11** or **Direct3D12** under **Unity 2019.3.0f3**.

Work great with **Vulkan** through !

Sorry for not being able to pinpoint where is the problem.

**Comment by kirurobo** [comment]
Try disabling "Use DXGI Flip Model Swapchain for DXD11" in the "Resolution and Presentation" section of the player settings.

I updated WindowController's auto validation for it.

**Comment by kirurobo** [comment]
This setting can now be applied in the inspector of the WindowController.
Thank you!

![validation](https://user-images.githubusercontent.com/1019117/89745778-fecbd980-daf0-11ea-87cc-f3a3e7b2b0a5.png)
